# -*- coding: utf-8 -*-
"""Lab_1_Recursion

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19zM1lOP5HALJ1SDlI5vsD6VUEldWiKBD

Name : Harsh Dineshkumar Patel    
No.  : AU2140022     
Data Structure Section-1
"""

#Program 1

n = int(input("Enter a Number: "))

def factorial(x):

    if x == 1 or x==0:
        return 1
    else:
        # recursive call to the function
        return (x * factorial(x-1))

m = factorial(n)
  
print(m)

#Program 2

def first():
    second()
    print("I am the first")

def second():
    third()
    print("I am second")

def third():
    fourth()
    print("I am third")

def fourth():
    print("I am fourth")

first()
print("\t")

second()
print("\t")

third()
print("\t")

fourth()

#Program 3

n = int(input("Enter a Number: "))

def addup(x):
  m =0
  while x>0:
    m = m+x 
    x-=1
  return m


k = addup(n)
print(k)

#Program 4

n = int(input("Enter a number: "))

def fib(x):
  
  if x == 1:
    return 0
  if x==2:
    return 1
  return fib(x-1)+fib(x-2)

fib(n)

#Program 5

n = [8,4,5]
m=[]

def prodArray(x):
  
  if len(x) == 0:
    return 1
  return x[len(x)-1]*prodArray(x[:-1])


prodArray(n)

#Program 6

def HCF(a,b):
  if a==0:
    return b
  return HCF(b%a,a)


HCF(24,46)

#Program 7

def IsPali(str):
  rev = ""
  for i in str:
    rev = i + rev
  
  if str == rev:
    print("True")
  else:
    print("False")

IsPali("harsh")
IsPali("malayalam")

#Program 8

def reverse(str): 
   rev = " "
   for i in str:

     rev = i + rev

   return rev

reverse("string")